// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd8hrWu0MxP4v-bi-_1KYLJ0QZGVuTC9k',
    appId: '1:131922956457:web:6b699fb23a58d8f4b4d9b8',
    messagingSenderId: '131922956457',
    projectId: 'flutter-login-app-81735',
    authDomain: 'flutter-login-app-81735.firebaseapp.com',
    storageBucket: 'flutter-login-app-81735.appspot.com',
    measurementId: 'G-CQHZYQY8EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgQxDSNgSn1twCaB-fqZ-65_uKIuRCZfI',
    appId: '1:131922956457:android:a92e1654374b9ee9b4d9b8',
    messagingSenderId: '131922956457',
    projectId: 'flutter-login-app-81735',
    storageBucket: 'flutter-login-app-81735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFG6rhYqsyuscEhu8tSxf7QcN0BCj5n-A',
    appId: '1:131922956457:ios:66b1047988594599b4d9b8',
    messagingSenderId: '131922956457',
    projectId: 'flutter-login-app-81735',
    storageBucket: 'flutter-login-app-81735.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFG6rhYqsyuscEhu8tSxf7QcN0BCj5n-A',
    appId: '1:131922956457:ios:93106f33fc62d1bbb4d9b8',
    messagingSenderId: '131922956457',
    projectId: 'flutter-login-app-81735',
    storageBucket: 'flutter-login-app-81735.appspot.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
